AWSTemplateFormatVersion: "2010-09-09"
Description: QR Upload WebSocket Event Handler Lambda Function

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
    Description: Environment name

  ProjectName:
    Type: String
    Default: qr-upload
    Description: Project name for resource naming

  WebSocketEventLambdaRoleArn:
    Type: String
    Description: ARN of the WebSocket/Event Lambda execution role

  SessionsTableName:
    Type: String
    Description: Name of the DynamoDB sessions table

  UploadsBucketName:
    Type: String
    Description: Name of the uploads S3 bucket

  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing Lambda deployment package

  LambdaZipFile:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /qr-upload/websocket-event-handler/lambda-zip
    Description: SSM parameter name containing Lambda zip file name

Resources:
  WebSocketEventLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-websocket-event-${Environment}"
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: !Ref WebSocketEventLambdaRoleArn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "lambda-zip/websocket-event-handler/${LambdaZipFile}"
      Environment:
        Variables:
          SESSIONS_TABLE_NAME: !Ref SessionsTableName
          UPLOAD_BUCKET_NAME: !Ref UploadsBucketName
      Description: WebSocket and S3 event handler for QR upload

  WebSocketEventLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${WebSocketEventLambdaFunction}"
      RetentionInDays: 7

Outputs:
  WebSocketEventLambdaFunctionArn:
    Description: ARN of the WebSocket Event Lambda function
    Value: !GetAtt WebSocketEventLambdaFunction.Arn

  WebSocketEventLambdaFunctionName:
    Description: Name of the WebSocket Event Lambda function
    Value: !Ref WebSocketEventLambdaFunction
