AWSTemplateFormatVersion: "2010-09-09"
Description: Main stack for QR Upload (nested stacks)

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
    Description: Environment name

  ProjectName:
    Type: String
    Default: qr-upload
    Description: Project name for resource naming

  LambdaCodeBucket:
    Type: String
    Default: cf-templates--1tlzie64y9rw-us-east-1
    Description: S3 bucket containing Lambda deployment packages

  WsApiEndpoint:
    Type: String
    Default: "r0k1fs92k5.execute-api.us-east-1.amazonaws.com/production"
    Description: WebSocket API endpoint (format api-id.execute-api.region.amazonaws.com/stage) - Update after creating WebSocket API Gateway

  WebSocketEventLambdaFunctionArn:
    Type: String
    Default: "arn:aws:lambda:us-east-1:905418207079:function:qr-upload-websocket-event-dev"
    Description: Websocket event lambda arn to be used by the uploads s3 buckets

Resources:
  InfraAssetsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates--1tlzie64y9rw-us-east-1.s3.us-east-1.amazonaws.com/qr-upload/qr-infra-assets.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        UploadEventLambdaArn: !Ref WebSocketEventLambdaFunctionArn

  HttpApiLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraAssetsStack
    Properties:
      TemplateURL: https://cf-templates--1tlzie64y9rw-us-east-1.s3.us-east-1.amazonaws.com/qr-upload/qr-lambda-http-api.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        HttpApiLambdaRoleArn: !GetAtt InfraAssetsStack.Outputs.HttpApiLambdaRoleArn
        SessionsTableName: !GetAtt InfraAssetsStack.Outputs.SessionsTableName
        UploadsBucketName: !GetAtt InfraAssetsStack.Outputs.UploadsBucketName
        LambdaCodeBucket: !Ref LambdaCodeBucket

  WebSocketEventLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraAssetsStack
    Properties:
      TemplateURL: https://cf-templates--1tlzie64y9rw-us-east-1.s3.us-east-1.amazonaws.com/qr-upload/qr-lambda-websocket-event.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        WebSocketEventLambdaRoleArn: !GetAtt InfraAssetsStack.Outputs.WebSocketEventLambdaRoleArn
        SessionsTableName: !GetAtt InfraAssetsStack.Outputs.SessionsTableName
        UploadsBucketName: !GetAtt InfraAssetsStack.Outputs.UploadsBucketName
        LambdaCodeBucket: !Ref LambdaCodeBucket
        WsApiEndpoint: !Ref WsApiEndpoint

Outputs:
  WebsiteBucketName:
    Description: Website hosting bucket name
    Value: !GetAtt InfraAssetsStack.Outputs.WebsiteBucketName

  WebsiteUrl:
    Description: Website URL
    Value: !GetAtt InfraAssetsStack.Outputs.WebsiteUrl

  UploadsBucketName:
    Description: Uploads bucket name
    Value: !GetAtt InfraAssetsStack.Outputs.UploadsBucketName

  SessionsTableName:
    Description: DynamoDB sessions table name
    Value: !GetAtt InfraAssetsStack.Outputs.SessionsTableName

  HttpApiLambdaRoleArn:
    Description: ARN of HTTP API Lambda execution role
    Value: !GetAtt InfraAssetsStack.Outputs.HttpApiLambdaRoleArn

  WebSocketEventLambdaRoleArn:
    Description: ARN of WebSocket/Event Lambda execution role
    Value: !GetAtt InfraAssetsStack.Outputs.WebSocketEventLambdaRoleArn

  HttpApiLambdaFunctionName:
    Description: Name of the HTTP API Lambda function
    Value: !GetAtt HttpApiLambdaStack.Outputs.HttpApiLambdaFunctionName

  WebSocketEventLambdaFunctionName:
    Description: Name of the WebSocket Event Lambda function
    Value: !GetAtt WebSocketEventLambdaStack.Outputs.WebSocketEventLambdaFunctionName
