AWSTemplateFormatVersion: "2010-09-09"
Description: Main stack for QR Upload (nested stacks)

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
    Description: Environment name

  ProjectName:
    Type: String
    Default: qr-upload
    Description: Project name for resource naming

  LambdaCodeBucket:
    Type: String
    Default: cf-templates--1tlzie64y9rw-us-east-1
    Description: S3 bucket containing Lambda deployment packages

Resources:
  InfraAssetsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates--1tlzie64y9rw-us-east-1.s3.us-east-1.amazonaws.com/qr-upload/qr-infra-assets.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName

  HttpApiLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraAssetsStack
    Properties:
      TemplateURL: https://cf-templates--1tlzie64y9rw-us-east-1.s3.us-east-1.amazonaws.com/qr-upload/qr-lambda-http-api.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        HttpApiLambdaRoleArn: !GetAtt InfraAssetsStack.Outputs.HttpApiLambdaRoleArn
        SessionsTableName: !GetAtt InfraAssetsStack.Outputs.SessionsTableName
        UploadsBucketName: !GetAtt InfraAssetsStack.Outputs.UploadsBucketName
        LambdaCodeBucket: !Ref LambdaCodeBucket

  WebSocketEventLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: InfraAssetsStack
    Properties:
      TemplateURL: https://cf-templates--1tlzie64y9rw-us-east-1.s3.us-east-1.amazonaws.com/qr-upload/qr-lambda-websocket-event.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        WebSocketEventLambdaRoleArn: !GetAtt InfraAssetsStack.Outputs.WebSocketEventLambdaRoleArn
        SessionsTableName: !GetAtt InfraAssetsStack.Outputs.SessionsTableName
        UploadsBucketName: !GetAtt InfraAssetsStack.Outputs.UploadsBucketName
        LambdaCodeBucket: !Ref LambdaCodeBucket

Outputs:
  WebsiteBucketName:
    Description: Website hosting bucket name
    Value: !GetAtt InfraAssetsStack.Outputs.WebsiteBucketName

  WebsiteUrl:
    Description: Website URL
    Value: !GetAtt InfraAssetsStack.Outputs.WebsiteUrl

  UploadsBucketName:
    Description: Uploads bucket name
    Value: !GetAtt InfraAssetsStack.Outputs.UploadsBucketName

  SessionsTableName:
    Description: DynamoDB sessions table name
    Value: !GetAtt InfraAssetsStack.Outputs.SessionsTableName

  HttpApiLambdaRoleArn:
    Description: ARN of HTTP API Lambda execution role
    Value: !GetAtt InfraAssetsStack.Outputs.HttpApiLambdaRoleArn

  WebSocketEventLambdaRoleArn:
    Description: ARN of WebSocket/Event Lambda execution role
    Value: !GetAtt InfraAssetsStack.Outputs.WebSocketEventLambdaRoleArn

  HttpApiLambdaFunctionArn:
    Description: ARN of the HTTP API Lambda function
    Value: !GetAtt HttpApiLambdaStack.Outputs.HttpApiLambdaFunctionArn

  HttpApiLambdaFunctionName:
    Description: Name of the HTTP API Lambda function
    Value: !GetAtt HttpApiLambdaStack.Outputs.HttpApiLambdaFunctionName

  WebSocketEventLambdaFunctionArn:
    Description: ARN of the WebSocket Event Lambda function
    Value: !GetAtt WebSocketEventLambdaStack.Outputs.WebSocketEventLambdaFunctionArn

  WebSocketEventLambdaFunctionName:
    Description: Name of the WebSocket Event Lambda function
    Value: !GetAtt WebSocketEventLambdaStack.Outputs.WebSocketEventLambdaFunctionName
